
branches:
  only:
    - master

language: node_js

node_js:
  - node

install:
  - npm install

script:
  - npm run build

deploy:
  provider: pages
  local-dir: dist
  skip-cleanup: true
  github-token: $GH_TOKEN  # Set in travis-ci.org dashboard, marked secure
  target-branch: gh-pages
  keep-history: true
  on:
    branch: master

